version: 2
updates:
  # Maintain GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  # Maintain Python dependencies (pip)
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'weekly'

  # Maintain JavaScript dependencies (npm)
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
