[tool.pylint.messages_control]
disable = [
    "C0103", "C0104", "C0114", "C0115", "C0116", "C0206", "C0413", "C1803",
    "C0121", "E0401", "E0611", "E1101", "E1102", "R0402", "R0801", "R0902",
    "R0903", "R0912", "R0913", "R0914", "R0915", "R1732", "W0104", "W0212",
    "W0612", "W0613", "W0621", "W0718", "W1404", "W1514",
    "C0301", "C0303", "C0415", "W0611", "W1203", "W1309",
    "R0917"  # too-many-positional-arguments (new in pylint 3)
]

[tool.pylint.format]
max-line-length = 100

[tool.black]
line-length = 100
target-version = ['py39']
