name: Notify Slack

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    if: secrets.SLACK_WEBHOOK_URL != ''
    steps:
      - name: Send Slack notification
        continue-on-error: true
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: '{"text":"A new push to main branch!"}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
